server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://oddscalc.cv2qlth3lytm.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=public #can hardcode credentials, but better practice to use environment variables to not expose creds
    username: Scrumbob
    password: Devpants
#  datasource:
#    url: ${db_url} #can hardcode credentials, but better practice to use environment variables to not expose creds
#    username: ${db_user}
#    password: ${db_pass}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  
  
 # h2:
  #  console:
   #   enabled: true
