<<<<<<< HEAD
server:
  port: 8080


=======
#server:
#  port: 8080
#
#spring:
##  datasource:
##    url: jdbc:postgresql://oddscalc.cv2qlth3lytm.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=public #can hardcode credentials, but better practice to use environment variables to not expose creds
##    username: Scrumbob
##    password: Devpants
>>>>>>> ba65b3663afa42bfe9b1faffdbb3d340c7e53eb8
#  datasource:
#    url: ${db_url} #can hardcode credentials, but better practice to use environment variables to not expose creds
#    username: ${db_user}
#    password: ${db_pass}

spring:


<<<<<<< HEAD

spring:

   datasource:
     url: jdbc:postgresql://oddscalc.cv2qlth3lytm.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=public #can hardcode credentials, but better practice to use environment variables to not expose creds
     username: Scrumbob
     password: Devpants
   jpa:
     show-sql: true
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       ddl-auto: none
=======
#   datasource:
#     url: jdbc:postgresql://oddscalc.cv2qlth3lytm.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=public #can hardcode credentials, but better practice to use environment variables to not expose creds
#     username: Scrumbob
#     password: Devpants
#   jpa:
#     show-sql: true
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: none
>>>>>>> ba65b3663afa42bfe9b1faffdbb3d340c7e53eb8

  
  
h2:
    console:
      enabled: true

jackson:
   serialization:
      fail-on-empty-beans: false
profiles:
    active:
    - "@profileActive@"
#
## Actuator setting to display more metrics about the application
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

