server:
  port: 8080

spring:

  datasource:
    url: ${db_url} #can hardcode credentials, but better practice to use environment variables to not expose creds
    username: ${db_user}
    password: ${db_pass}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  

  
#h2:
#    console:
#      enabled: true
#
#jackson:
#   serialization:
#      fail-on-empty-beans: false
#profiles:
#    active:
#    - "@profileActive@"
#
## Actuator setting to display more metrics about the application
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

